/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminKpisRouteImport } from './routes/_authenticated/admin_.kpis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminKpisRoute = AuthenticatedAdminKpisRouteImport.update({
  id: '/admin_/kpis',
  path: '/admin/kpis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/gracias': typeof GraciasRoute
  '/panel': typeof PanelRoute
  '/privacidad': typeof PrivacidadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/kpis': typeof AuthenticatedAdminKpisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/gracias': typeof GraciasRoute
  '/panel': typeof PanelRoute
  '/privacidad': typeof PrivacidadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/kpis': typeof AuthenticatedAdminKpisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/gracias': typeof GraciasRoute
  '/panel': typeof PanelRoute
  '/privacidad': typeof PrivacidadRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin_/kpis': typeof AuthenticatedAdminKpisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/gracias'
    | '/panel'
    | '/privacidad'
    | '/admin'
    | '/admin/kpis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/gracias'
    | '/panel'
    | '/privacidad'
    | '/admin'
    | '/admin/kpis'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookies'
    | '/gracias'
    | '/panel'
    | '/privacidad'
    | '/_authenticated/admin'
    | '/_authenticated/admin_/kpis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  GraciasRoute: typeof GraciasRoute
  PanelRoute: typeof PanelRoute
  PrivacidadRoute: typeof PrivacidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/kpis': {
      id: '/_authenticated/admin_/kpis'
      path: '/admin/kpis'
      fullPath: '/admin/kpis'
      preLoaderRoute: typeof AuthenticatedAdminKpisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminKpisRoute: typeof AuthenticatedAdminKpisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminKpisRoute: AuthenticatedAdminKpisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  GraciasRoute: GraciasRoute,
  PanelRoute: PanelRoute,
  PrivacidadRoute: PrivacidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
